TITLE: Open Blog Revolution #Blog title
URL: 'https://open-blog-revolution.netlify.app/' # Blog url, we use it to generate sitemap
BASE: '' # Blog base folder is any, most of the timme just ''
DESCRIPTION: Free blog template # Blog descriptioj
LANG: EN # Blog language
DATE_LANG: fr # Blog date format fr for dd/mm/yyyy en-US for mm/dd/yyyy
STYLE: sans # Defaut blog style sans | serif | sans-and-serif | serif-and-sans
AUTHOR: Iko # Author name
CONTACT: true # Set to false to omit email/contact link in header
EMAIL: youremail@email.com # Email
POST_COVER: true # Show post cover in post page
# MY_SWITCH: true #uncomment to add additional link to header.
# MY_LINK: https://link.to.something #copy structure for further links.
# Edit also relevant parts in 'src/types/config.d.ts' and 'src/components/header.astro'.
POST_THUMBNAILS: true # Show post cover in lists of posts 
POST_SUGGESTIONS: true # Suggest more posts to read based on tags
HOME_NB_POSTS: 6 # Number of posts to show on the home page
MENU: # Main menu 
  - label: RSS # Example menu label
    url: rss.xml # Example menu url
  - label: Archive # Example menu label
    url: archive # Example menu url
  - label: Blogroll # Example menu label
    url: blogroll # Example menu url
BLOG_COVER:  # Blog cover for social networks previews
  src: obr_large.png # Cover url (must be placed in the folder src/public)
  alt: Open Blog Revolution # Cover image alt text, mandatory
BANNER: # Blog banner, appears above the menu if any
  src: obr_banner.png  # Banner url (must be placed in the folder src/media)
  alt: Open Blog Revolution Banner # Banner image alt text, mandatory